### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by srt** [asciidoctor/atom-asciidoc-preview#52]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app/src/atom.js:55:11)
Object.changeRenderMode (/home/srt/.atom/packages/asciidoc-preview/lib/asciidoc-preview.coffee:164:23)
```

The atom.syntax global is deprecated. Use atom.grammars instead.
```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app/src/atom.js:316:11)
AsciiDocPreviewView.handleEvents (/home/srt/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:72:20)
```

Using Atom 0.175.0

**Comment by anthonny** [comment]
Hi @srt !
Thank you for having filled this issue :+1:, it should be fixed with 0.4.3

**Comment by royemmerich** [comment]
I'm still getting this issue popping up with atom 0.182.0 and atom-asciidoc-preview 0.4.3

It seems to be affecting the render on save only functionality which is no longer working.

**Comment by anthonny** [comment]
My bad ... you're right, there's still a warning, I missed this case

**Comment by royemmerich** [comment]
This error still comes about when running:

Atom: 0.186.0
atom-asciidoc-preview: 0.4.3

atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/opt/atom/resources/app/src/atom.js:54:11)
HTMLAnchorElement.<anonymous> (/home/roy/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:276:35)
```

**Comment by anthonny** [comment]
Hi @royemmerich,

This issue should be fixed with the 0.5.0, feel free to reopen if necessary
