### ISSUE TITLE
Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

### ISSUE THREAD

**Issue by AndyGee** [asciidoctor/atom-asciidoc-preview#55]
In stylesheets\asciidoc-preview.less: Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.
If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

**Comment by anthonny** [comment]
Hi @AndyGee 
Thank you for having filled this issue :+1:, it should be fixed with 0.4.3

**Comment by JanJean** [comment]
OS : Linux
Atom-Version : 0.188.0
Asciidoc-Preview-Version : 0.4.3

Problem still exists with 0.4.3
I've delete configuration-folder $HOME/.atom and used clean (fresh) plugin-installation for asciidoc-preview.

**Comment by JanJean** [comment]
I've updatet Atom-Editor from 0.181.0 to 0.182.0.
It works now. (solved)

**Comment by mojavelinux** [comment]
:+1:
