### ISSUE TITLE
Failed to load the asciidoc-preview package

### ISSUE THREAD

**Issue by mnquintana** [asciidoctor/atom-asciidoc-preview#91]
[Enter steps to reproduce below:]

1. Make sure asciidoc-preview is activated
2. Open Atom in dev mode

**Atom Version**: 0.199.0-f1f8c3d
**System**: Mac OS X 10.10.3
**Thrown From**: [asciidoc-preview](https://github.com/asciidoctor/atom-asciidoc-preview) package, v0.5.0

### Stack Trace

Failed to load the asciidoc-preview package

```
At Cannot find module '/Users/machistequintana/github/highlights'

Error: Cannot find module '/Users/machistequintana/github/highlights'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Users/machistequintana/github/atom/src/module-cache.coffee:273:20)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/machistequintana/.atom/packages/asciidoc-preview/lib/renderer.coffee:8:14)
  at Object.<anonymous> (/Users/machistequintana/.atom/packages/asciidoc-preview/lib/renderer.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Users/machistequintana/github/atom/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/machistequintana/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:7:12)
  at Object.<anonymous> (/Users/machistequintana/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Users/machistequintana/github/atom/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/machistequintana/.atom/packages/asciidoc-preview/lib/asciidoc-preview.coffee:3:23)
  at Object.<anonymous> (/Users/machistequintana/.atom/packages/asciidoc-preview/lib/asciidoc-preview.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Users/machistequintana/github/atom/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Users/machistequintana/github/atom/src/package.coffee:430:21)
  at /Users/machistequintana/github/atom/src/package.coffee:129:10
  at Package.module.exports.Package.measure (/Users/machistequintana/github/atom/src/package.coffee:114:13)
  at Package.module.exports.Package.load (/Users/machistequintana/github/atom/src/package.coffee:123:6)
  at PackageManager.module.exports.PackageManager.loadPackage (/Users/machistequintana/github/atom/src/package-manager.coffee:330:12)
  at PackageManager.module.exports.PackageManager.loadPackages (/Users/machistequintana/github/atom/src/package-manager.coffee:309:6)
  at Atom.module.exports.Atom.startEditorWindow (/Users/machistequintana/github/atom/src/atom.coffee:589:15)
  at Object.<anonymous> (/Users/machistequintana/github/atom/src/window-bootstrap.coffee:7:6)
  at Object.<anonymous> (/Users/machistequintana/github/atom/src/window-bootstrap.coffee:2:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Users/machistequintana/github/atom/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///Users/machistequintana/github/atom/static/index.js:86:23)
  at window.onload (file:///Users/machistequintana/github/atom/static/index.js:38:7)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "script",
      "sublime-tabs",
      "linter-shellcheck",
      "linter-jshint",
      "linter-rubocop"
    ],
    "destroyEmptyPanes": false,
    "audioBeep": false
  },
  "asciidoc-preview": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
asciidoc-preview, v0.5.0
autocomplete-atom-api, v0.9.0
autocomplete-css, v0.7.2
autocomplete-emojis, v2.2.1
autocomplete-paths, v1.0.2
autocomplete-plus, v2.13.1
autocomplete-snippets, v1.5.1
carto-atom, v0.4.0
color-picker, v1.7.0
editorconfig, v1.0.0
file-icons, v1.5.5
git-tab-status, v1.7.0
language-asciidoc, v0.11.1
language-haml, v0.20.0
language-jade, v0.4.0
linter, v0.12.2
linter-coffeelint, v0.2.3
linter-csslint, v0.0.12
linter-eslint, v0.5.4
linter-js-yaml, v1.0.0
linter-jscs, v1.11.0
minimap, v4.8.0
minimap-git-diff, v4.1.2
pigments, v0.2.0
travis-ci-status, v0.14.0

# Dev
bracket-matcher, v0.74.0
encoding-selector, v0.20.0
fuzzy-finder, v0.72.0
markdown-preview, v0.148.0
minimap, v4.8.0
settings-view, v0.195.0
tabs, v0.68.0
tree-view, v0.172.0
welcome, v0.27.0
wrap-guide, v0.32.0
```

**Comment by mnquintana** [comment]
Looks like it's because of this line: https://github.com/asciidoctor/atom-asciidoc-preview/blob/d21db8c73f869e082bd86a1f4d3265010930e0bb/lib/renderer.coffee#L8

In dev mode this resolves to your project path.

**Comment by boggle** [comment]
So how do I fix this? Have to work with asciidoc a lot and this has been open for all atom asciidoc modules for month.

**Comment by boggle** [comment]
I'll +1 this one more time.

**Comment by anthonny** [comment]
Hi @boggle 

@mnquintana is right, it's because your atom is in dev mode. There is no workaround :(, i must fix that sorry

**Comment by ldez** [comment]
FIxed in 1.0.2

**Comment by testn** [comment]
I still see the problem on 2.9.0 version.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [asciidoc-preview](https://github.com/asciidoctor/atom-asciidoc-preview) package 2.9.0


### Stack Trace

Failed to load the asciidoc-preview package

```
At '../node_modules/asciidoctor.js/dist/css/asciidoctor.css' wasn't found in /Users/nluengna/.atom/packages/asciidoc-preview/styles/asciidoc-preview.less:10:2

LessError: '../node_modules/asciidoctor.js/dist/css/asciidoctor.css' wasn't found
  at /packages/asciidoc-preview/styles/asciidoc-preview.less:10:2
```

### Commands

```
  2x -0:54.9.0 nuclide-home:toggle (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
asciidoc-preview 2.9.0 
atom-beautify undefined 
autocomplete 0.47.0 
autocomplete-go 1.3.0 
builder-go 1.0.1 
color-picker 2.2.5 
environment 1.3.1 
git-plus 7.3.3 
go-config 1.2.4 
go-get 2.1.1 
go-plus 5.3.3 
gofmt 1.2.0 
gometalinter-linter 1.2.2 
gorename 1.1.0 
hex 0.6.2 
language-asciidoc 1.8.0 
linter 2.1.0 
markdown-preview-plus 2.4.9 
markdown-writer 2.6.4 
merge-conflicts 1.4.4 
minimap 4.26.8 
navigator-go 1.1.3 
navigator-godef 1.0.3 
nuclide 0.205.0 
pigments 0.39.0 
tester-go 2.0.2 
```

**Comment by ldez** [comment]
@testn open a new issue please.

**Comment by ldez** [comment]
@testn it's not the same problem.
